version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: echo "Hello, World"
      - run: echo "${CIRCLE_BRANCH}"
      - run: echo "${CIRCLE_TAG}"
      - run: echo "${CIRCLE_TAG:-${CIRCLE_BRANCH}}"
      - run:
          command: |
            mkdir -p /tmp/workspace/build
            echo "awesome artifact" > /tmp/workspace/build/output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - build/*
  deploy:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/build/output.txt
      - run:
          name: deploy
          command: |
            [ "${CIRCLE_TAG}" != "" ] && TAG=${CIRCLE_TAG} || TAG=latest
            echo "Deploy! ${TAG}"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v.*/
            branches:
              only: master
